### ISSUE TITLE
Make lsq vocab deref

### ISSUE THREAD

**Issue by gatemezing** [AKSW/LSQ#2]
Hi @saleem-muhammad, could it be possible to make the vocab lsq (http://lsq.aksw.org/vocab#) dereferenceable in order to be inserted into LOV dataset?

**Comment by saleem-muhammad** [comment]
Hi. Please have a look  now if this is what you mean. thanks

**Comment by gatemezing** [comment]
Thanks for your quick answer. Still getting some issues with content type in the response, see vapour's report http://tinyurl.com/jbutlvx. Also in the first triple of the ontology,
[ 

```
<http://lsq.aksw.org/vocab#>
  a owl:Ontology . 
```

]  I would suggest to use the URI of the vocab, not the namespace...sth like

[

```
<http://lsq.aksw.org/vocab>
  a owl:Ontology .
```

]

WDY?

**Comment by aidhog** [comment]
Yes, we should at least pass all the tests for "Dereferencing Entity URI (requesting RDF/XML)". Thanks for the report!

@gatemezing, I'm curious though why you prefer the IRI without the hash for the ontology? I added it since I think the ontology is different from the document, e.g., the ontology in that document could change at some point. What do you think?

**Comment by gatemezing** [comment]
@aidhog Well! I think you can handle the versioning in different ways using the same IRI. One way could be to have more metadata such as `owl:priorVersion, owl:versionInfo`...and more provenance info (dct:modified, etc..). Of course, you can make some cool conneg to retrieve the current version of the vocab with links to different previous version as with w3c docs.

**Comment by Aklakan** [comment]
Hi Ghislain, I removed the # from the vocab url part and fixed the proxy settings, and http://tinyurl.com/jbutlvx now succeeds in regard to you minimal requirements so I think your issue is now resloved? :)

**Comment by gatemezing** [comment]
Hi Claus, good to know that you are around ;)
Thanks for fixing.. That seems to be a first step. Btw, could you renamed the file to be just https://cdn.rawgit.com/AKSW/LSQ/gh-pages/LSQ_Vocab.rdf instead of https://cdn.rawgit.com/AKSW/LSQ/gh-pages/LSQ_Vocab.rdf.xml

**Comment by Aklakan** [comment]
Hi Ghislain, good to see you around here as well ;) The file was renamed, so I think now its possible to close the issue? ;)

**Comment by gatemezing** [comment]
Yes @Aklakan ;)
