### ISSUE TITLE
Errors in some subjects and objects

### ISSUE THREAD

**Issue by noorbakerally** [AKSW/LSQ#3]
Getting errors when loading linkedgeodata with fuseki,

`error example: Caused by: org.apache.jena.riot.RiotException: [line: 1402014, col: 35] Triples not terminated by DOT
`
on this line, the object is`lsqr:-anon-1`

**Comment by saleem-muhammad** [comment]
Hi, 
Thanks for opening the issue. Seems like there is some syntax error. I am travelling now and will have a look to this issue next week.

**Comment by saleem-muhammad** [comment]
I had a look at the issue. It seems the fuseki parser is too strict even to the characters used within literals. I have fixed and uploaded the new dump. Please have a look and let me whether it works or not.
