### ISSUE TITLE
Integrate FedX

### ISSUE THREAD

**Issue by Aklakan** [AKSW/LSQ#4]
In the FedX source `src/org/aksw/simba/start/QueryEvaluation.java` make loadEndpoints fetch data from a file passed as a command line argument to LSQ.
Then use this endpoint for query execution.

As the FedX code is based on Sesame, whereas LSQ is Jena based, possibly this wrapper could be used: https://github.com/afs/JenaSesame

**Comment by saleem-muhammad** [comment]
done.
