### ISSUE TITLE
spring-core dependency

### ISSUE THREAD

**Issue by adibaba** [AKSW/LSQ#7]
I got an error while building several lsq-sub-projects.
Maven was not able to find spring-core.

After changing

```
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>4.3.18</version>
            </dependency>
```
back to
```
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>4.3.5.RELEASE</version>
            </dependency>
```
the build process finishes.

This change is based on the commit https://github.com/AKSW/LSQ/commit/69a0d10f93a288745d9d8ca9c8084ec4e3541e88

**Comment by xqx1568** [comment]
Thank you very much.I'm not familiar with maven project, you save me a lot of time.

**Comment by Aklakan** [comment]
spring is currently not used anymore in lsq. It may become reinstated as a separate 'lsq-spring-integration' module; but core modules depending on spring have always resulted in pain.
